#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 
bspc monitor DP-5 -d 
bspc monitor DP-3 -d 

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move

xrandr --output DP-5 --mode 1920x1080 --pos 0x0 --rotate inverted --output DP-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal --output DP-3 --mode 1920x1080 --pos 1920x275 --rotate right

polybar &
picom &
