#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr \
  --output DP-1 --mode 1920x1080 --pos 1080x1080 --rotate normal --primary \
  --output DP-5 --mode 1920x1080 --pos 1080x0 --rotate inverted \
  --output DP-3 --mode 1920x1080 --pos 0x275 --rotate left

bspc monitor DP-3 -d 
bspc monitor DP-1 -d 
bspc monitor DP-5 -d 

bspc wm -O DP-3 DP-1 DP-5

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move

polybar &
picom &
