#!/usr/bin/env sh

THEME_ROUTE="$HOME/.local/custom-themes"

pkill -USR1 -x polybar

feh --bg-scale $THEME_ROUTE/tree-house-day/wallpaper.png
polybar -c=$THEME_ROUTE/tree-house-day/config.ini -q example &
